chords = {
    'MAJOR': {'ROOT', 'MAJOR 3RD', 'PERFECT 5TH'},
    'MINOR': {'ROOT', 'MINOR 3RD', 'PERFECT 5TH'},
    'AUGMENTED': {'ROOT', 'MAJOR 3RD', 'AUGMENTED 5TH'},
    'DIMINISHED': {'ROOT', 'MINOR 3RD', 'DIMINISHED 5TH'},

    'DOM7': {'ROOT', 'MAJOR 3RD', 'PERFECT 5TH', 'MINOR 7TH'},
    'DIM7': {'ROOT', 'MINOR 3RD', 'DIMINISHED 5TH', 'DIMINISHED 7TH'},
    'HALFDIM7': {'ROOT', 'MINOR 3RD', 'DIMINISHED 5TH', 'MINOR 7TH'},
    'MIN7': {'ROOT', 'MINOR 3RD', 'PERFECT 5TH', 'MINOR 7TH'},
    'MINMAJ7': {'ROOT', 'MINOR 3RD', 'PERFECT 5TH', 'MAJOR 7TH'},
    'MAJ7': {'ROOT', 'MAJOR 3RD', 'PERFECT 5TH', 'MAJOR 7TH'},
    'AUG7': {'ROOT', 'MAJOR 3RD', 'AUGMENTED 5TH', 'MINOR 7TH'},
    'AUGMAJ7': {'ROOT', 'MAJOR 3RD', 'AUGMENTED 5TH', 'MAJOR 7TH'},

}
