chords = {
    'MAJOR': {'ROOT', 'MAJOR 3RD', 'PERFECT 5TH'},
    'MINOR': {'ROOT', 'MINOR 3RD', 'PERFECT 5TH'},
    'AUGMENTED': {'ROOT', 'MAJOR 3RD', 'AUGMENTED 5TH'},
    'DIMINISHED': {'ROOT', 'MINOR 3RD', 'DIMINISHED 5TH'},

    'DOMINANT 7TH': {'ROOT', 'MAJOR 3RD', 'PERFECT 5TH', 'MINOR 7TH'},
    'DIMINISHED 7TH': {'ROOT', 'MINOR 3RD', 'DIMINISHED 5TH', 'DIMINISHED 7TH'},
    'HALF-DIMINISHED 7TH': {'ROOT', 'MINOR 3RD', 'DIMINISHED 5TH', 'MINOR 7TH'},
    'MINOR 7TH': {'ROOT', 'MINOR 3RD', 'PERFECT 5TH', 'MINOR 7TH'},
    'MINOR MAJOR 7TH': {'ROOT', 'MINOR 3RD', 'PERFECT 5TH', 'MAJOR 7TH'},
    'MAJOR 7TH': {'ROOT', 'MAJOR 3RD', 'PERFECT 5TH', 'MAJOR 7TH'},
    'AUGMENTED 7TH': {'ROOT', 'MAJOR 3RD', 'AUGMENTED 5TH', 'MINOR 7TH'},
    'AUGMENTED MAJOR 7TH': {'ROOT', 'MAJOR 3RD', 'AUGMENTED 5TH', 'MAJOR 7TH'},

    'DOMINANT 7#9': {'ROOT', 'MAJOR 3RD', 'PERFECT 5TH', 'MINOR 7TH',
                     'AUGMENTED 2ND'},

    'DOMINANT 9TH': {'ROOT', 'MAJOR 3RD', 'PERFECT 5TH', 'MINOR 7TH',
                     'MAJOR 9TH'},
    'DOMINANT 11TH': {'ROOT', 'MAJOR 3RD', 'PERFECT 5TH', 'MINOR 7TH',
                      'MAJOR 9TH', 'PERFECT 11TH'},
    'DOMINANT 13TH': {'ROOT', 'MAJOR 3RD', 'PERFECT 5TH', 'MINOR 7TH',
                      'MAJOR 9TH', 'PERFECT 11TH', 'MAJOR 13th'},

    'ADD 9': {'ROOT', 'MAJOR 3RD', 'PERFECT 5TH', 'MAJOR 9TH'},
    'ADD 4': {'ROOT', 'MAJOR 3RD', 'PERFECT 5TH', 'PERFECT 4TH'},
    'ADD 6': {'ROOT', 'MAJOR 3RD', 'PERFECT 5TH', 'MAJOR 6TH'},
    '6/9': {'ROOT', 'MAJOR 3RD', 'PERFECT 5TH', 'MAJOR 6TH', 'MAJOR 9TH'},
    '7/6': {'ROOT', 'MAJOR 3RD', 'PERFECT 5TH', 'MAJOR 6TH', 'MINOR 7TH'},
    'MIXED 3RD': {'ROOT', 'MAJOR 3RD', 'PERFECT 5TH', 'MINOR 3RD'},

    'SUSPENDED 2ND': {'ROOT', 'MAJOR 2ND', 'PERFECT 5TH'},
    'SUSPENDED 4TH': {'ROOT', 'PERFECT 4TH', 'PERFECT 5TH'},
    'JAZZ SUS': {'ROOT', 'PERFECT 4TH', 'PERFECT 5TH', 'MINOR 7TH',
                 'MAJOR 9TH'},

    'MAJOR 7♯11': {'ROOT', 'MAJOR 3RD', 'PERFECT 5TH', 'MAJOR 7TH', 'SHARP 11TH'},

    'MAJOR 6TH': {'ROOT', 'MAJOR 3RD', 'PERFECT 5TH', 'MAJOR 6TH'},
    'MINOR MAJOR 6TH': {'ROOT', 'MINOR 3RD', 'PERFECT 5TH', 'MAJOR 6TH'},

    # '': {},
}
